#!/bin/bash

# Copyright 2018 Splunk

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

SPLUNK_PRODUCT = splunk
SPLUNK_VERSION = 7.2.3
SPLUNK_BUILD = 06d57c595b80
SPLUNK_ARCH = x86_64
SPLUNK_LINUX_FILENAME = splunk-${SPLUNK_VERSION}-${SPLUNK_BUILD}-Linux-${SPLUNK_ARCH}.tgz
SPLUNK_LINUX_BUILD_URL = https://download.splunk.com/products/${SPLUNK_PRODUCT}/releases/${SPLUNK_VERSION}/linux/${SPLUNK_LINUX_FILENAME}


echo "Downloading Splunk and validating the checksum at: ${SPLUNK_BUILD_URL}"
wget -qO /tmp/${SPLUNK_FILENAME} ${SPLUNK_BUILD_URL}
wget -qO /tmp/${SPLUNK_FILENAME}.sha512 ${SPLUNK_BUILD_URL}.sha512
sha512sum -c ${SPLUNK_FILENAME}.sha512
tar -zxfv ${SPLUNK_FILENAME} -C /opt
